### ISSUE TITLE
Can you change SleekXMPP (dead project) to Slixmpp (Successor)

### ISSUE THREAD

**Issue by Neustradamus** [immanuelfodor/xmpp-muc-message-gateway#1]
Can you update the code for compatibility with the successor of SleekXMPP?
- https://lab.louiz.org/poezio/slixmpp
- https://github.com/poezio/slixmpp

**Comment by immanuelfodor** [comment]
Thanks for the heads-up, I was not aware of the archival of SleekXMPP.

The new release is switched to the new SliXMPP, however, it should be working just as before, no other changes to functionality: https://github.com/immanuelfodor/xmpp-muc-message-gateway/releases/tag/v1.1.0

**Comment by Neustradamus** [comment]
@immanuelfodor: Thanks a lot!
